services:
  camera:
    image: ghcr.io/ca1ebd/yolo-rpicam:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /run/udev:/run/udev:ro
      - ./output:/output
    privileged: true
    ipc: host
